In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import re
import seaborn as sns
import warnings
pd.set_option('display.float_format', lambda x : '%.30f' % x)
pd.options.display.max_columns = None
pd.options.display.float_format = "{:,.3f}".format
warnings.filterwarnings('ignore')
sns.set()

In [2]:
dataset = pd.read_excel("220216 - Trial Balance & Reporting - General Ledger Report - S_ALR_87012289 - to 31st December 2021.xls.xlsx",header  = None)

In [3]:
tbr = dataset
tbr

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
0,nan,CoCd,DocumentNo,NaN,nan,Year,NaN,nan,Type,Pstng Date,NaN,Document Status,NaN,nan,NaN,nan,NaN,Reference,NaN,nan,nan,NaN,Rev. with,nan,Year,Crcy,NaN,Doc.No. GL,GLFY,User Name
1,nan,AccTy,NaN,Account,nan,NaN,PstKy (Sub,nan,NaN,NaN,Amount in LC (FC),NaN,Tax Line I,nan,Amount (Tax Line),nan,Tx,PK,G/L,nan,nan,LC Amount,NaN,nan,NaN,NaN,GL Itm,NaN,NaN,NaN
2,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,nan,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
3,nan,UK01,2000,NaN,nan,2021,NaN,nan,A,01.01.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,STAT. BU,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,BREITENBACHS
4,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,40,520003,nan,nan,12500,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177178,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,50,99999,nan,nan,-20.710,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
177179,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,50,99100,nan,nan,-20.710,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
177180,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,40,98100,nan,nan,13.440,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
177181,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,40,99999,nan,nan,20.710,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
177182,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,40,800216,nan,nan,20.710,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
tbr1 = tbr.loc[tbr[29].notnull() == True]
tbr1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
0,nan,CoCd,DocumentNo,NaN,nan,Year,NaN,nan,Type,Pstng Date,NaN,Document Status,NaN,nan,NaN,nan,NaN,Reference,NaN,nan,nan,NaN,Rev. with,nan,Year,Crcy,NaN,Doc.No. GL,GLFY,User Name
3,nan,UK01,2000,NaN,nan,2021,NaN,nan,A,01.01.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,STAT. BU,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,BREITENBACHS
9,nan,UK01,2001,NaN,nan,2021,NaN,nan,A,31.03.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,2021-03-01 00:00:00,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,BREITENBACHS
13,nan,UK01,2002,NaN,nan,2021,NaN,nan,A,30.04.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,2021-04-01 00:00:00,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,BREITENBACHS
17,nan,UK01,2003,NaN,nan,2021,NaN,nan,A,31.05.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,2021-05-01 00:00:00,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,BREITENBACHS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177138,nan,UK01,9900000002,NaN,nan,2021,NaN,nan,RR,30.09.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,MAISELN
177150,nan,UK01,9900000003,NaN,nan,2021,NaN,nan,RR,31.10.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,WERNERA
177158,nan,UK01,9900000004,NaN,nan,2021,NaN,nan,RR,30.11.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,LEXAMA
177167,nan,UK01,9900000005,NaN,nan,2021,NaN,nan,RR,31.12.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,MAISELN
177176,nan,UK01,9900000006,NaN,nan,2021,NaN,nan,RR,31.12.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,MAISELN

In [5]:
tbr1.drop([0,1,3,4,6,7,10,12,13,14,15,16,18,19,20,21,23,26,27,28], inplace = True , axis = 1)

In [6]:
data1 = tbr1.values.tolist()
heading1 = data1[0]
data1 = data1[1:]
len(data1)

38121

In [7]:
index_drop = tbr.loc[tbr[10].str.endswith(")") == True].index
index_drop

Int64Index([     1,  70268,  70272,  70274,  70339,  70343,  70347,  70461,
             70465,  70469,
            ...
            176561, 176566, 176614, 176618, 176620, 176624, 176626, 176698,
            176787, 177017],
           dtype='int64', length=2085)

In [8]:
tbr.drop(index_drop)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
0,nan,CoCd,DocumentNo,NaN,nan,Year,NaN,nan,Type,Pstng Date,NaN,Document Status,NaN,nan,NaN,nan,NaN,Reference,NaN,nan,nan,NaN,Rev. with,nan,Year,Crcy,NaN,Doc.No. GL,GLFY,User Name
2,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,nan,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
3,nan,UK01,2000,NaN,nan,2021,NaN,nan,A,01.01.2021,NaN,NaN,NaN,nan,NaN,nan,NaN,STAT. BU,NaN,nan,nan,NaN,NaN,nan,NaN,GBP,NaN,NaN,NaN,BREITENBACHS
4,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,40,520003,nan,nan,12500,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
5,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,50,530003,nan,nan,-12500,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177178,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,50,99999,nan,nan,-20.710,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
177179,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,50,99100,nan,nan,-20.710,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
177180,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,40,98100,nan,nan,13.440,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
177181,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,40,99999,nan,nan,20.710,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN
177182,nan,NaN,NaN,NaN,nan,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,NaN,nan,NaN,40,800216,nan,nan,20.710,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
tbr2 = tbr.drop([0,2,4,5,7,8,9,11,13,15,17,19,20,22,23,24,25,26,27,28,29],axis = 1)
# heading2 = tbr2[1:2]

heading2 = tbr2[1:2].values.tolist()[0]
# tbr2[1:2]1	3	6	10	12	14	16	18	21

In [10]:
tbr2.loc[
        (tbr[10].notnull() == True) & \
        (tbr[18].notnull() == False)
]

         1       3    6                           10   12   14   16   18   21
70268   NaN     NaN  NaN               (EUR 324.42-)  NaN  NaN  NaN  NaN  NaN
70273     D  358813   15                  -5,899.900  NaN  NaN  NaN  NaN  NaN
70274   NaN     NaN  NaN             (EUR 6,522.83-)  NaN  NaN  NaN  NaN  NaN
71566   NaN     NaN  NaN             (EUR 6,554.94-)  NaN  NaN  NaN  NaN  NaN
71756   NaN     NaN  NaN             (EUR 9,534.50-)  NaN  NaN  NaN  NaN  NaN
...     ...     ...  ...                         ...  ...  ...  ...  ...  ...
177023    D  425519   17                  -1,989.900  NaN  NaN  NaN  NaN  NaN
177041    D   90724    7                     754.910  NaN  NaN  NaN  NaN  NaN
177051    D  507110   17                     -97.690  NaN  NaN  NaN  NaN  NaN
177055    D  507110   17                    -188.280  NaN  NaN  NaN  NaN  NaN
177059    D  507110   17                     -62.110  NaN  NaN  NaN  NaN  NaN

[1734 rows x 9 columns]

In [11]:
tbr2 = tbr2.loc[
        (tbr[1].notnull() == True)| \
        (tbr[3].notnull() == True)| \
        (tbr[6].notnull() == True)| \
        (tbr[12].notnull() == True)| \
        (tbr[16].notnull() == True)| \
        (tbr[18].notnull() == True)| \
        (tbr[21].notnull() == True)| \
        (tbr[14].notnull() == True)]

In [12]:
heading2

['AccTy',
 'Account',
 'PstKy (Sub',
 'Amount in LC (FC)',
 'Tax Line I',
 'Amount (Tax Line)',
 'Tx',
 'G/L',
 'LC Amount']

In [13]:
tbr2.drop(1,axis = 0,inplace = True)
tbr2.reset_index(drop = True, inplace= True)

In [14]:
tbr2.columns = heading2
tbr2

,AccTy,Account,PstKy (Sub,Amount in LC (FC),Tax Line I,Amount (Tax Line),Tx,G/L,LC Amount
0,CoCd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UK01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520003,12500
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530003,-12500
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520020,"7,166.670"
...,...,...,...,...,...,...,...,...,...
137912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99999,-20.710
137913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99100,-20.710
137914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98100,13.440
137915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99999,20.710
137916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800216,20.710

In [15]:
tbr2.drop(0,inplace=True)

In [16]:
tbr2

,AccTy,Account,PstKy (Sub,Amount in LC (FC),Tax Line I,Amount (Tax Line),Tx,G/L,LC Amount
1,UK01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520003,12500
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530003,-12500
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520020,"7,166.670"
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530020,"-7,166.670"
...,...,...,...,...,...,...,...,...,...
137912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99999,-20.710
137913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99100,-20.710
137914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98100,13.440
137915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99999,20.710
137916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800216,20.710

In [17]:
len(data1),data1

(38121,
 [[2000,
   2021,
   'A',
   '01.01.2021',
   nan,
   'STAT. BU',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [2001,
   2021,
   'A',
   '31.03.2021',
   nan,
   datetime.datetime(2021, 3, 1, 0, 0),
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [2002,
   2021,
   'A',
   '30.04.2021',
   nan,
   datetime.datetime(2021, 4, 1, 0, 0),
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [2003,
   2021,
   'A',
   '31.05.2021',
   nan,
   datetime.datetime(2021, 5, 1, 0, 0),
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [2004,
   2021,
   'A',
   '30.06.2021',
   nan,
   datetime.datetime(2021, 6, 1, 0, 0),
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [2005,
   2021,
   'A',
   '31.07.2021',
   nan,
   datetime.datetime(2021, 7, 1, 0, 0),
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [2006,
   2021,
   'A',
   '31.08.2021',
   nan,
   datetime.datetime(2021, 8, 1, 0, 0),
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [2007,
   2021,
   'A',
   '30.09.2021',
   nan,
   datetime.datetime(2021, 9, 1, 0, 0),
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [2008,
   2021,
   'A',
   '31.10.2021',
   nan,
   datetime.datetime(2021, 10, 1, 0, 0),
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [2009,
   2021,
   'A',
   '30.11.2021',
   nan,
   datetime.datetime(2021, 11, 1, 0, 0),
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [2010,
   2021,
   'A',
   '31.12.2021',
   nan,
   datetime.datetime(2021, 12, 1, 0, 0),
   2011,
   2021,
   'GBP',
   'WENZLS'],
  [2011,
   2021,
   'A',
   '31.12.2021',
   nan,
   datetime.datetime(2021, 12, 1, 0, 0),
   2010,
   2021,
   'GBP',
   'WENZLS'],
  [2012,
   2021,
   'A',
   '31.12.2021',
   nan,
   datetime.datetime(2021, 12, 1, 0, 0),
   nan,
   nan,
   'GBP',
   'WENZLS'],
  [7000,
   2021,
   'LG',
   '28.01.2021',
   nan,
   'JAN2021 PENSION',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7001,
   2021,
   'LG',
   '28.01.2021',
   nan,
   'HMRC PAYE/NI',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7002,
   2021,
   'LG',
   '15.01.2021',
   nan,
   'LG 01/2021',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [7003,
   2021,
   'LG',
   '28.02.2021',
   nan,
   'HMRC PAYE/NI',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7004, 2021, 'LG', '28.02.2021', nan, nan, nan, nan, 'GBP', 'HAWKESWORTHJ'],
  [7005,
   2021,
   'LG',
   '15.02.2021',
   nan,
   'LG 02/2021',
   7006,
   2021,
   'GBP',
   'BREITENBACHS'],
  [7006,
   2021,
   'LG',
   '28.02.2021',
   nan,
   'LG 02/2021',
   7005,
   2021,
   'GBP',
   'BREITENBACHS'],
  [7007,
   2021,
   'LG',
   '15.02.2021',
   nan,
   'LG 02/2021',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [7008,
   2021,
   'LG',
   '29.03.2021',
   nan,
   'HMRC PAYE/NI',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7009, 2021, 'LG', '29.03.2021', nan, nan, nan, nan, 'GBP', 'HAWKESWORTHJ'],
  [7011,
   2021,
   'LG',
   '15.03.2021',
   nan,
   'LG 03/2021',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [7012,
   2021,
   'LG',
   '19.04.2021',
   nan,
   'HMRC PAYE/NI',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7013,
   2021,
   'LG',
   '19.04.2021',
   nan,
   'APR2021 PENSION',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7014,
   2021,
   'LG',
   '15.04.2021',
   nan,
   'LG 04/2021',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [7015,
   2021,
   'LG',
   '17.05.2021',
   nan,
   'HMRC PAYE/NI',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7016,
   2021,
   'LG',
   '17.05.2021',
   nan,
   'MAY2021 PENSION',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7017,
   2021,
   'LG',
   '15.05.2021',
   nan,
   'LG 05/2021',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [7018,
   2021,
   'LG',
   '21.06.2021',
   nan,
   'HMRC PAYE/NI',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7019, 2021, 'LG', '21.06.2021', nan, nan, nan, nan, 'GBP', 'HAWKESWORTHJ'],
  [7020,
   2021,
   'LG',
   '15.06.2021',
   nan,
   'LG 06/2021',
   nan,
   nan,
   'GBP',
   'WENZLS'],
  [7021,
   2021,
   'LG',
   '22.07.2021',
   nan,
   'HMRC PAYE/NI',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7022,
   2021,
   'LG',
   '22.07.2021',
   nan,
   'JUL21 PENSION',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7023,
   2021,
   'LG',
   '15.07.2021',
   nan,
   'LG 07/2021',
   nan,
   nan,
   'GBP',
   'WENZLS'],
  [7024,
   2021,
   'LG',
   '19.08.2021',
   nan,
   'HMRC PAYE/NI',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7025, 2021, 'LG', '19.08.2021', nan, nan, nan, nan, 'GBP', 'HAWKESWORTHJ'],
  [7026,
   2021,
   'LG',
   '15.08.2021',
   nan,
   'LG 08/2021',
   nan,
   nan,
   'GBP',
   'WENZLS'],
  [7027,
   2021,
   'LG',
   '24.09.2021',
   nan,
   'SEPT2021 PENSON',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7028,
   2021,
   'LG',
   '24.09.2021',
   nan,
   'HMRC PAYE/NI',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7029,
   2021,
   'LG',
   '15.09.2021',
   nan,
   'LG 09/2021',
   nan,
   nan,
   'GBP',
   'WENZLS'],
  [7030,
   2021,
   'LG',
   '28.10.2021',
   nan,
   'HMRC PAYE/NI',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7031,
   2021,
   'LG',
   '28.10.2021',
   nan,
   'OCT21 PENSION',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [7032,
   2021,
   'LG',
   '15.10.2021',
   nan,
   'LG 10/2021',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [7033, 2021, 'LG', '30.11.2021', nan, nan, nan, nan, 'GBP', 'HAWKESWORTHJ'],
  [7034, 2021, 'LG', '30.11.2021', nan, nan, nan, nan, 'GBP', 'HAWKESWORTHJ'],
  [7035,
   2021,
   'LG',
   '15.11.2021',
   nan,
   'LG 11/2021',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [7036,
   2021,
   'LG',
   '15.12.2021',
   nan,
   'LG 12/2021',
   7037,
   2021,
   'GBP',
   'BREITENBACHS'],
  [7037,
   2021,
   'LG',
   '15.12.2021',
   nan,
   'LG 12/2021',
   7036,
   2021,
   'GBP',
   'BREITENBACHS'],
  [7038,
   2021,
   'LG',
   '15.12.2021',
   nan,
   'LG 12/2021',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [7039, 2021, 'LG', '31.12.2021', nan, nan, nan, nan, 'GBP', 'HAWKESWORTHJ'],
  [7040, 2021, 'LG', '31.12.2021', nan, nan, nan, nan, 'GBP', 'HAWKESWORTHJ'],
  [7041,
   2021,
   'LG',
   '31.12.2021',
   nan,
   'DEC2019 PENSION2',
   nan,
   nan,
   'GBP',
   'HAWKESWORTHJ'],
  [30000, 2021, 'SA', '31.01.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30001, 2021, 'SA', '28.02.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30002, 2021, 'SA', '31.03.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30003, 2021, 'SA', '30.04.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30004, 2021, 'SA', '31.05.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30005, 2021, 'SA', '01.06.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30006, 2021, 'SA', '30.06.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30007,
   2021,
   'SA',
   '01.07.2021',
   nan,
   'CORR. REP. 20',
   30029,
   2020,
   'GBP',
   'BREITENBACHS'],
  [30008, 2021, 'SA', '31.07.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30009, 2021, 'SA', '31.08.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30010, 2021, 'SA', '30.09.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30011, 2021, 'SA', '31.10.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30012, 2021, 'SA', '30.11.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30013, 2021, 'SA', '01.12.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30014, 2021, 'SA', '15.12.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30015, 2021, 'SA', '31.12.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30016, 2021, 'SA', '31.12.2021', nan, nan, nan, nan, 'GBP', 'WENZLS'],
  [30017, 2021, 'SA', '31.12.2021', nan, 400571492, nan, nan, 'GBP', 'HILDN'],
  [30018,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'CORRECTION',
   nan,
   nan,
   'GBP',
   'WENZLS'],
  [30019, 2021, 'SA', '31.12.2021', nan, nan, nan, nan, 'GBP', 'WENZLS'],
  [30020,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB1',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30021,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB2',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30022,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB3',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30023,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB4',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30024,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB5',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30025,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB6',
   30001,
   2022,
   'GBP',
   'BREITENBACHS'],
  [30026,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB7',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30027,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB8',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30028,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB9',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30029,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB10',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30030,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB11',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30031,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB12',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30032,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB13',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30033,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB14',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [30034, 2021, 'SA', '31.12.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [30035,
   2021,
   'SA',
   '31.12.2021',
   nan,
   'NB KST',
   nan,
   nan,
   'GBP',
   'BREITENBACHS'],
  [50000, 2021, 'B1', '04.01.2021', nan, 1, nan, nan, 'GBP', 'BREITENBACHS'],
  [50001, 2021, 'B1', '04.01.2021', nan, 1, nan, nan, 'GBP', 'BREITENBACHS'],
  [50002, 2021, 'B1', '04.01.2021', nan, 1, nan, nan, 'GBP', 'BREITENBACHS'],
  [50003, 2021, 'B1', '04.01.2021', nan, 1, nan, nan, 'GBP', 'BREITENBACHS'],
  [50004, 2021, 'B1', '05.01.2021', nan, 2, nan, nan, 'GBP', 'BREITENBACHS'],
  [50005, 2021, 'B1', '05.01.2021', nan, 2, nan, nan, 'GBP', 'BREITENBACHS'],
  [50006, 2021, 'B1', '05.01.2021', nan, 2, nan, nan, 'GBP', 'BREITENBACHS'],
  [50007, 2021, 'B1', '06.01.2021', nan, 3, nan, nan, 'GBP', 'BREITENBACHS'],
  [50008, 2021, 'B1', '06.01.2021', nan, 3, nan, nan, 'GBP', 'BREITENBACHS'],
  [50009, 2021, 'B1', '06.01.2021', nan, 3, nan, nan, 'GBP', 'BREITENBACHS'],
  [50010, 2021, 'B1', '07.01.2021', nan, 4, nan, nan, 'GBP', 'BREITENBACHS'],
  [50011, 2021, 'B1', '08.01.2021', nan, 5, nan, nan, 'GBP', 'BREITENBACHS'],
  [50012, 2021, 'B1', '08.01.2021', nan, 5, nan, nan, 'GBP', 'BREITENBACHS'],
  [50013, 2021, 'B1', '08.01.2021', nan, 5, nan, nan, 'GBP', 'BREITENBACHS'],
  [50014, 2021, 'B1', '11.01.2021', nan, 6, nan, nan, 'GBP', 'BREITENBACHS'],
  [50015, 2021, 'B1', '11.01.2021', nan, 6, nan, nan, 'GBP', 'BREITENBACHS'],
  [50016, 2021, 'B1', '12.01.2021', nan, 7, nan, nan, 'GBP', 'BREITENBACHS'],
  [50017, 2021, 'B1', '12.01.2021', nan, 7, nan, nan, 'GBP', 'BREITENBACHS'],
  [50018, 2021, 'B1', '12.01.2021', nan, 7, nan, nan, 'GBP', 'BREITENBACHS'],
  [50019, 2021, 'B1', '12.01.2021', nan, 7, nan, nan, 'GBP', 'BREITENBACHS'],
  [50020, 2021, 'B1', '13.01.2021', nan, 8, nan, nan, 'GBP', 'BREITENBACHS'],
  [50021, 2021, 'B1', '13.01.2021', nan, 8, nan, nan, 'GBP', 'BREITENBACHS'],
  [50022, 2021, 'B1', '13.01.2021', nan, 8, nan, nan, 'GBP', 'BREITENBACHS'],
  [50023, 2021, 'B1', '14.01.2021', nan, 9, nan, nan, 'GBP', 'WENZLS'],
  [50024, 2021, 'B1', '14.01.2021', nan, 9, nan, nan, 'GBP', 'WENZLS'],
  [50025, 2021, 'B1', '14.01.2021', nan, 9, nan, nan, 'GBP', 'WENZLS'],
  [50026, 2021, 'B1', '15.01.2021', nan, 10, nan, nan, 'GBP', 'WENZLS'],
  [50027, 2021, 'B1', '15.01.2021', nan, 10, nan, nan, 'GBP', 'WENZLS'],
  [50028, 2021, 'B1', '15.01.2021', nan, 10, nan, nan, 'GBP', 'WENZLS'],
  [50029, 2021, 'B1', '15.01.2021', nan, 10, nan, nan, 'GBP', 'WENZLS'],
  [50030, 2021, 'B1', '18.01.2021', nan, 11, nan, nan, 'GBP', 'WENZLS'],
  [50031, 2021, 'B1', '18.01.2021', nan, 11, nan, nan, 'GBP', 'WENZLS'],
  [50032, 2021, 'B1', '18.01.2021', nan, 11, nan, nan, 'GBP', 'WENZLS'],
  [50033, 2021, 'B1', '19.01.2021', nan, 12, nan, nan, 'GBP', 'WENZLS'],
  [50034, 2021, 'B1', '19.01.2021', nan, 12, nan, nan, 'GBP', 'WENZLS'],
  [50035, 2021, 'B1', '19.01.2021', nan, 12, nan, nan, 'GBP', 'WENZLS'],
  [50036, 2021, 'B1', '20.01.2021', nan, 13, nan, nan, 'GBP', 'WENZLS'],
  [50037, 2021, 'B1', '20.01.2021', nan, 13, nan, nan, 'GBP', 'WENZLS'],
  [50038, 2021, 'B1', '20.01.2021', nan, 13, nan, nan, 'GBP', 'WENZLS'],
  [50039, 2021, 'B1', '21.01.2021', nan, 14, nan, nan, 'GBP', 'WENZLS'],
  [50040, 2021, 'B1', '21.01.2021', nan, 14, nan, nan, 'GBP', 'WENZLS'],
  [50041, 2021, 'B1', '22.01.2021', nan, 15, nan, nan, 'GBP', 'WENZLS'],
  [50042, 2021, 'B1', '22.01.2021', nan, 15, nan, nan, 'GBP', 'WENZLS'],
  [50043, 2021, 'B1', '22.01.2021', nan, 15, nan, nan, 'GBP', 'WENZLS'],
  [50044, 2021, 'B1', '25.01.2021', nan, 16, nan, nan, 'GBP', 'WENZLS'],
  [50045, 2021, 'B1', '25.01.2021', nan, 16, nan, nan, 'GBP', 'WENZLS'],
  [50046, 2021, 'B1', '25.01.2021', nan, 16, nan, nan, 'GBP', 'WENZLS'],
  [50047, 2021, 'B1', '25.01.2021', nan, 16, nan, nan, 'GBP', 'WENZLS'],
  [50048, 2021, 'B1', '26.01.2021', nan, 17, nan, nan, 'GBP', 'WENZLS'],
  [50049, 2021, 'B1', '26.01.2021', nan, 17, nan, nan, 'GBP', 'WENZLS'],
  [50050, 2021, 'B1', '27.01.2021', nan, 18, nan, nan, 'GBP', 'WENZLS'],
  [50051, 2021, 'B1', '27.01.2021', nan, 18, nan, nan, 'GBP', 'WENZLS'],
  [50052, 2021, 'B1', '27.01.2021', nan, 18, nan, nan, 'GBP', 'WENZLS'],
  [50053, 2021, 'B1', '27.01.2021', nan, 18, nan, nan, 'GBP', 'WENZLS'],
  [50054, 2021, 'B1', '28.01.2021', nan, 19, nan, nan, 'GBP', 'WENZLS'],
  [50055, 2021, 'B1', '28.01.2021', nan, 19, nan, nan, 'GBP', 'WENZLS'],
  [50056, 2021, 'B1', '28.01.2021', nan, 19, nan, nan, 'GBP', 'WENZLS'],
  [50057, 2021, 'B1', '28.01.2021', nan, 19, nan, nan, 'GBP', 'WENZLS'],
  [50058, 2021, 'B1', '29.01.2021', nan, 20, nan, nan, 'GBP', 'WENZLS'],
  [50059, 2021, 'B1', '29.01.2021', nan, 20, nan, nan, 'GBP', 'WENZLS'],
  [50060, 2021, 'B1', '29.01.2021', nan, 20, nan, nan, 'GBP', 'WENZLS'],
  [50061, 2021, 'B1', '01.02.2021', nan, 21, nan, nan, 'GBP', 'WENZLS'],
  [50062, 2021, 'B1', '01.02.2021', nan, 21, nan, nan, 'GBP', 'WENZLS'],
  [50063, 2021, 'B1', '01.02.2021', nan, 21, nan, nan, 'GBP', 'WENZLS'],
  [50064, 2021, 'B1', '01.02.2021', nan, 21, nan, nan, 'GBP', 'WENZLS'],
  [50065, 2021, 'B1', '02.02.2021', nan, 22, nan, nan, 'GBP', 'WENZLS'],
  [50066, 2021, 'B1', '02.02.2021', nan, 22, nan, nan, 'GBP', 'WENZLS'],
  [50067, 2021, 'B1', '02.02.2021', nan, 22, nan, nan, 'GBP', 'WENZLS'],
  [50068, 2021, 'B1', '03.02.2021', nan, 23, nan, nan, 'GBP', 'WENZLS'],
  [50069, 2021, 'B1', '03.02.2021', nan, 23, nan, nan, 'GBP', 'WENZLS'],
  [50070, 2021, 'B1', '03.02.2021', nan, nan, nan, nan, 'GBP', 'BREITENBACHS'],
  [50071, 2021, 'B1', '04.02.2021', nan, 24, nan, nan, 'GBP', 'WENZLS'],
  [50072, 2021, 'B1', '04.02.2021', nan, 24, nan, nan, 'GBP', 'WENZLS'],
  [50073, 2021, 'B1', '04.02.2021', nan, 24, nan, nan, 'GBP', 'WENZLS'],
  [50074, 2021, 'B1', '05.02.2021', nan, 25, nan, nan, 'GBP', 'WENZLS'],
  [50075, 2021, 'B1', '05.02.2021', nan, 25, nan, nan, 'GBP', 'WENZLS'],
  [50076, 2021, 'B1', '05.02.2021', nan, 25, nan, nan, 'GBP', 'WENZLS'],
  [50077, 2021, 'B1', '08.02.2021', nan, 26, nan, nan, 'GBP', 'WENZLS'],
  [50078, 2021, 'B1', '08.02.2021', nan, 26, nan, nan, 'GBP', 'WENZLS'],
  [50079, 2021, 'B1', '09.02.2021', nan, 27, nan, nan, 'GBP', 'WENZLS'],
  [50080, 2021, 'B1', '09.02.2021', nan, 27, nan, nan, 'GBP', 'WENZLS'],
  [50081, 2021, 'B1', '10.02.2021', nan, 28, nan, nan, 'GBP', 'WENZLS'],
  [50082, 2021, 'B1', '10.02.2021', nan, 28, nan, nan, 'GBP', 'WENZLS'],
  [50083, 2021, 'B1', '11.02.2021', nan, 29, nan, nan, 'GBP', 'BREITENBACHS'],
  [50084, 2021, 'B1', '11.02.2021', nan, 29, nan, nan, 'GBP', 'BREITENBACHS'],
  [50085, 2021, 'B1', '12.02.2021', nan, 30, nan, nan, 'GBP', 'BREITENBACHS'],
  [50086, 2021, 'B1', '12.02.2021', nan, 30, nan, nan, 'GBP', 'BREITENBACHS'],
  [50087, 2021, 'B1', '12.02.2021', nan, 30, nan, nan, 'GBP', 'BREITENBACHS'],
  [50088, 2021, 'B1', '15.02.2021', nan, 31, nan, nan, 'GBP', 'WENZLS'],
  [50089, 2021, 'B1', '15.02.2021', nan, 31, nan, nan, 'GBP', 'WENZLS'],
  [50090, 2021, 'B1', '15.02.2021', nan, 31, nan, nan, 'GBP', 'WENZLS'],
  [50091, 2021, 'B1', '15.02.2021', nan, 31, nan, nan, 'GBP', 'WENZLS'],
  [50092, 2021, 'B1', '16.02.2021', nan, 32, nan, nan, 'GBP', 'WENZLS'],
  [50093, 2021, 'B1', '16.02.2021', nan, 32, nan, nan, 'GBP', 'WENZLS'],
  [50094, 2021, 'B1', '17.02.2021', nan, 33, nan, nan, 'GBP', 'WENZLS'],
  [50095, 2021, 'B1', '17.02.2021', nan, 33, nan, nan, 'GBP', 'WENZLS'],
  [50096, 2021, 'B1', '17.02.2021', nan, 33, nan, nan, 'GBP', 'WENZLS'],
  [50097, 2021, 'B1', '18.02.2021', nan, 34, nan, nan, 'GBP', 'WENZLS'],
  [50098, 2021, 'B1', '18.02.2021', nan, 34, nan, nan, 'GBP', 'WENZLS'],
  [50099, 2021, 'B1', '19.02.2021', nan, 35, nan, nan, 'GBP', 'WENZLS'],
  [50100, 2021, 'B1', '22.02.2021', nan, 36, nan, nan, 'GBP', 'WENZLS'],
  [50101, 2021, 'B1', '22.02.2021', nan, 36, nan, nan, 'GBP', 'WENZLS'],
  [50102, 2021, 'B1', '22.02.2021', nan, 36, nan, nan, 'GBP', 'WENZLS'],
  [50103, 2021, 'B1', '23.02.2021', nan, 37, nan, nan, 'GBP', 'WENZLS'],
  [50104, 2021, 'B1', '23.02.2021', nan, 37, nan, nan, 'GBP', 'WENZLS'],
  [50105, 2021, 'B1', '23.02.2021', nan, 37, nan, nan, 'GBP', 'WENZLS'],
  [50106, 2021, 'B1', '24.02.2021', nan, 38, nan, nan, 'GBP', 'WENZLS'],
  [50107, 2021, 'B1', '24.02.2021', nan, 38, nan, nan, 'GBP', 'WENZLS'],
  [50108, 2021, 'B1', '25.02.2021', nan, 39, nan, nan, 'GBP', 'WENZLS'],
  [50109, 2021, 'B1', '25.02.2021', nan, 39, nan, nan, 'GBP', 'WENZLS'],
  [50110, 2021, 'B1', '26.02.2021', nan, 40, nan, nan, 'GBP', 'WENZLS'],
  [50111, 2021, 'B1', '26.02.2021', nan, 40, nan, nan, 'GBP', 'BREITENBACHS'],
  [50112, 2021, 'B1', '01.03.2021', nan, 41, nan, nan, 'GBP', 'WENZLS'],
  [50113, 2021, 'B1', '01.03.2021', nan, 41, nan, nan, 'GBP', 'WENZLS'],
  [50114, 2021, 'B1', '01.03.2021', nan, 41, nan, nan, 'GBP', 'WENZLS'],
  [50115, 2021, 'B1', '02.03.2021', nan, 42, nan, nan, 'GBP', 'WENZLS'],
  [50116, 2021, 'B1', '03.03.2021', nan, 43, nan, nan, 'GBP', 'WENZLS'],
  [50117, 2021, 'B1', '03.03.2021', nan, 43, nan, nan, 'GBP', 'WENZLS'],
  [50118, 2021, 'B1', '04.03.2021', nan, 44, nan, nan, 'GBP', 'EISMANNC'],
  [50119, 2021, 'B1', '04.03.2021', nan, 44, nan, nan, 'GBP', 'WENZLS'],
  [50120, 2021, 'B1', '04.03.2021', nan, 44, nan, nan, 'GBP', 'WENZLS'],
  [50121, 2021, 'B1', '05.03.2021', nan, 45, nan, nan, 'GBP', 'WENZLS'],
  [50122, 2021, 'B1', '05.03.2021', nan, nan, nan, nan, 'GBP', 'WENZLS'],
  [50123, 2021, 'B1', '05.03.2021', nan, 45, nan, nan, 'GBP', 'WENZLS'],
  [50124, 2021, 'B1', '08.03.2021', nan, 46, nan, nan, 'GBP', 'WENZLS'],
  [50125, 2021, 'B1', '08.03.2021', nan, 46, nan, nan, 'GBP', 'WENZLS'],
  [50126, 2021, 'B1', '08.03.2021', nan, 46, nan, nan, 'GBP', 'WENZLS'],
  [50127, 2021, 'B1', '09.03.2021', nan, 47, nan, nan, 'GBP', 'WENZLS'],
  [50128, 2021, 'B1', '09.03.2021', nan, 47, nan, nan, 'GBP', 'WENZLS'],
  [50129, 2021, 'B1', '10.03.2021', nan, 48, nan, nan, 'GBP', 'WENZLS'],
  [50130, 2021, 'B1', '10.03.2021', nan, 48, nan, nan, 'GBP', 'WENZLS'],
  [50131, 2021, 'B1', '10.03.2021', nan, 48, nan, nan, 'GBP', 'WENZLS'],
  [50132, 2021, 'B1', '11.03.2021', nan, 49, nan, nan, 'GBP', 'WENZLS'],
  [50133, 2021, 'B1', '11.03.2021', nan, nan, nan, nan, 'GBP', 'WENZLS'],
  [50134, 2021, 'B1', '12.03.2021', nan, 50, nan, nan, 'GBP', 'WENZLS'],
  [50135, 2021, 'B1', '12.03.2021', nan, 50, nan, nan, 'GBP', 'WENZLS'],
  [50136, 2021, 'B1', '12.03.2021', nan, 50, nan, nan, 'GBP', 'WENZLS'],
  [50137, 2021, 'B1', '12.03.2021', nan, 50, nan, nan, 'GBP', 'WENZLS'],
  [50138, 2021, 'B1', '15.03.2021', nan, 51, nan, nan, 'GBP', 'WENZLS'],
  [50139, 2021, 'B1', '15.03.2021', nan, 51, nan, nan, 'GBP', 'WENZLS'],

In [18]:
data2 = []
counter = -1
for i in tbr2.AccTy.fillna("-"):
    if i == "UK01":
        counter+=1
    else:
        data2.append(data1[counter])

In [19]:
len(data2)

99795

In [20]:
tbr2.AccTy == "UK01"

1          True
2         False
3         False
4         False
5         False
          ...
137912    False
137913    False
137914    False
137915    False
137916    False
Name: AccTy, Length: 137916, dtype: bool

In [21]:
tbr2.drop(tbr2.loc[tbr2.AccTy == "UK01"].index,inplace=True)

In [22]:
tbr2.__len__()

99795

In [23]:
tbr2.reset_index(drop=True,inplace=True)

In [24]:
df1 = pd.DataFrame(data2, columns = heading1)

In [25]:
df1

,DocumentNo,Year,Type,Pstng Date,Document Status,Reference,Rev. with,Year,Crcy,User Name
0,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS
1,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS
2,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS
3,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS
4,2001,2021,A,31.03.2021,nan,2021-03-01 00:00:00,nan,nan,GBP,BREITENBACHS
...,...,...,...,...,...,...,...,...,...,...
99790,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN
99791,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN
99792,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN
99793,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN
99794,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN

In [26]:
result = pd.concat([df1, tbr2], axis=1)
result

,DocumentNo,Year,Type,Pstng Date,Document Status,Reference,Rev. with,Year,Crcy,User Name,AccTy,Account,PstKy (Sub,Amount in LC (FC),Tax Line I,Amount (Tax Line),Tx,G/L,LC Amount
0,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520003,12500
1,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530003,-12500
2,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520020,"7,166.670"
3,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530020,"-7,166.670"
4,2001,2021,A,31.03.2021,nan,2021-03-01 00:00:00,nan,nan,GBP,BREITENBACHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,501506,"6,254.460"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99790,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99999,-20.710
99791,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99100,-20.710
99792,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98100,13.440
99793,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99999,20.710
99794,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800216,20.710

In [32]:
result.drop(result.loc[(result["Tax Line I"] == "X4") & (result.Tx != "X4")].index,inplace = True)

In [35]:
result.reset_index(drop = True)

,DocumentNo,Year,Type,Pstng Date,Document Status,Reference,Rev. with,Year,Crcy,User Name,AccTy,Account,PstKy (Sub,Amount in LC (FC),Tax Line I,Amount (Tax Line),Tx,G/L,LC Amount
0,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520003,12500
1,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530003,-12500
2,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520020,"7,166.670"
3,2000,2021,A,01.01.2021,nan,STAT. BU,nan,nan,GBP,BREITENBACHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530020,"-7,166.670"
4,2001,2021,A,31.03.2021,nan,2021-03-01 00:00:00,nan,nan,GBP,BREITENBACHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,501506,"6,254.460"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99783,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99999,-20.710
99784,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99100,-20.710
99785,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98100,13.440
99786,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99999,20.710
99787,9900000006,2021,RR,31.12.2021,nan,NaN,nan,nan,GBP,MAISELN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800216,20.710

In [34]:
result.to_excel("Alhumdulliah.xlsx")